In [2]:
# from these notes: https://mesozoic-egg.github.io/tinygrad-notes/shapetracker.html

from tinygrad import Tensor
from tinygrad.shape.shapetracker import ShapeTracker
from tinygrad.shape.view import View

In [33]:
t1 = Tensor.arange(start=0, stop=8, step=1)
t2 = Tensor(42)
print(t1.numpy())
print(t1.data()[0])

t3 = t1 * t2
print(t3.numpy())
print(t3.data()[5])


st = t3.lazydata.st
print(st)

v = ShapeTracker.from_shape((8,))

# print(v.[3]) # how to access the actuall underlying data?

print(v.expr_idxs()[0])
print(v.expr_idxs()[0].render())

v = v.reshape((2, 4))
print(v.expr_idxs()[0].render())

v = v.reshape((2,2,2))
print(v.expr_idxs()[0].render())


saving DiGraph with 3 nodes and 2 edges to /home/james/code/tinygrad/tinygrad/temp/net.uops.svg
[0 1 2 3 4 5 6 7]
0
saving DiGraph with 7 nodes and 7 edges to /home/james/code/tinygrad/tinygrad/temp/net.uops.svg
[  0  42  84 126 168 210 252 294]
210
ShapeTracker(views=(View(shape=(8,), strides=(1,), offset=0, mask=None, contiguous=True),))
<idx0[0-7]>
idx0
((idx0*4)+idx1)
((idx0*4)+(idx1*2)+idx2)


In [111]:
print("Tensor 1")
t1 = Tensor.arange(start=0, stop=8, step=1)
print(t1.numpy())
print(t1.data()[5])
print(t1.lazydata.st.views)
print(t1.lazydata.st.expr_idxs()[0].render())

print("\nTensor 1 - Reshape 2x4")
t2 = t1.reshape(2, 4)
print(t2.numpy())
print(t2.lazydata.st.views)
print(t2.lazydata.st.expr_idxs()[0].render())

print("\nTensor 1 - Reshape 2x2x2")
t3 = t1.reshape(2, 2, 2)
print(t3.numpy())
print(t3.lazydata.st.views)
print(t3.lazydata.st.expr_idxs()[0].render())

print("\nTensor 1 - Permute 2,1,0")
t4 = t3.permute((2,1,0))
print(t4.numpy())
print(t4.lazydata.st.views)

print("\nTensor 1 - Reshape 4x2")
t5 = t4.reshape(4, 2)
print(t5.numpy())
print(t5.lazydata.st.views)
print(t5.lazydata.st.expr_idxs()[0].render())

print(t5.lazydata.st.contiguous)
print(t5.shape)
print(t5.lazydata.st.size)


Tensor 1
[0 1 2 3 4 5 6 7]
5
(View(shape=(8,), strides=(1,), offset=0, mask=None, contiguous=True),)
idx0

Tensor 1 - Reshape 2x4
[[0 1 2 3]
 [4 5 6 7]]
(View(shape=(2, 4), strides=(4, 1), offset=0, mask=None, contiguous=True),)
((idx0*4)+idx1)

Tensor 1 - Reshape 2x2x2
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(View(shape=(2, 2, 2), strides=(4, 2, 1), offset=0, mask=None, contiguous=True),)
((idx0*4)+(idx1*2)+idx2)

Tensor 1 - Permute 2,1,0
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]
(View(shape=(2, 2, 2), strides=(1, 2, 4), offset=0, mask=None, contiguous=False),)

Tensor 1 - Reshape 4x2
[[0 4]
 [2 6]
 [1 5]
 [3 7]]
(View(shape=(2, 2, 2), strides=(1, 2, 4), offset=0, mask=None, contiguous=False), View(shape=(4, 2), strides=(2, 1), offset=0, mask=None, contiguous=True))
(((idx0%2)*2)+(idx0//2)+(idx1*4))
False
(4, 2)
8


In [93]:
shape = ShapeTracker.from_shape((4,2))
shape = shape.reshape((2,2,2))
shape = shape.reshape((2,4))
print(shape.views)

shape = shape.permute((1,0))
print(shape.views)
print(shape.expr_idxs()[0].render())

shape = shape.reshape((2,4))
print(shape.views)

print(shape.simplify())


(View(shape=(2, 4), strides=(4, 1), offset=0, mask=None, contiguous=True),)
(View(shape=(4, 2), strides=(1, 4), offset=0, mask=None, contiguous=False),)
((idx1*4)+idx0)
(View(shape=(4, 2), strides=(1, 4), offset=0, mask=None, contiguous=False), View(shape=(2, 4), strides=(4, 1), offset=0, mask=None, contiguous=True))
ShapeTracker(views=(View(shape=(4, 2), strides=(1, 4), offset=0, mask=None, contiguous=False), View(shape=(2, 4), strides=(4, 1), offset=0, mask=None, contiguous=True)))
